version: "3.9"

services:
  rest-server:
    build: .
    container_name: github_users_rest
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    command: ["./bin/server"] 

  grpc-server:
    build: .
    container_name: github_users_grpc
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mysql
      - redis
    ports:
      - "9090:9090"
    command: ["./bin/grpc-server"]

  mysql:
    image: mysql:8.0
    container_name: github_users_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD} 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: github_users_redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
